### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MylesBorins** [Sensebloom/OSCeleton#17]
latest build has been crashing on OSX with error "Segmentation fault"

Unsure what is causing this issue

**Comment by lwoodbury** [comment]
I'm getting segmentation faults mostly when there are multiple users and I'm tracking them uncalibrated. It seems to occur when someone steps out of range and then steps back in quickly. If you wait the 5 seconds or so for OSCeleton to stop sending coordinates and then re-enter the problem doesn't occur. Total guess, but it seems that re-rentering quickly results in an attempt to use memory that is already allocated as it tries to keep the same user number?

**Comment by lwoodbury** [comment]
PS - OSX 10.6.8 Osceleton 1.2.1

**Comment by lwoodbury** [comment]
Figuring that maybe this is a NITE issue. Just read that NITE 'manages the tagging of users in the scene and the acquisition and release of control between users' which seems to be where the fault lies.

**Comment by MylesBorins** [comment]
Hmmm... so would that mean it is out of our hands to fix?
maybe I need to make a shell script to run osceleton.. that automatically runs it again if it crash's... seems like a solution

**Comment by lwoodbury** [comment]
I have posted in the OpenNI forum, I'll report back if I find out anything more. 

Yeah, could set up a script, but it would take a few seconds to reinitialize and you lose your users numbers which is a bummer. Have been setting up a Windows machine today (also a bummer) so I'll see how that does with NITE, otherwise I think the Microsoft middleware library would sort the problem (PC only) and you don't have to pose like a cactus for it to pick you up.

**Comment by MylesBorins** [comment]
any word on the error?

**Comment by lwoodbury** [comment]
No-one wants to speak to me on the OpenNI group (and no-one wants to speak to us here!). Have used the same set up on a Windows machine (OpenNI, NITE) and there are no problems, seems very robust. That's going to be the solution for me for now, I'm guessing the problem lies with NITE on OSX but I'm no expert.

**Comment by MylesBorins** [comment]
Fair enough... I kind of feel like the owners of this project have some more
pressing things going on, but that's alright.  Unfortunately going PC really
isn't an option, so a little shell script will have to do.

**Comment by lwoodbury** [comment]
Yeah, I can't sniff at the amazing work that's gone on and the generosity to share it all, just wish my skills were good enough to help out more!

**Comment by lwoodbury** [comment]
New OSX version of NITE just released on http://www.openni.org/, probably won't get a chance to try it until Friday, but dying to see if it fixes the problem.

**Comment by MylesBorins** [comment]
This is exciting... will install and report back tomorrow

edit: gotta stop click that comment & close button

**Comment by lwoodbury** [comment]
Well it didn't do anything for me, still getting segfaults, boo.
