### ISSUE TITLE
Possibility of a preview window?

### ISSUE THREAD

**Issue by wayfarerboy** [Sensebloom/OSCeleton#4]
First of all, thanks so much for your software.  It's the first time I've managed to start developing with the Kinect without hacking away at a C++ file (without really knowing what I'm doing!)

I have a request, and I hope this is a suitable place to post it.  It would be very useful to have a preview window showing something similar to the Sample-Players example that comes with the Nite middleware.  Maybe it could be part of the command line options to turn on/off?

Not sure how easy this would be to implement, but it would be useful for participants to see their Psi calibration pose (and notice when Kinect has trouble capturing their movements).

**Comment by tonyfg** [comment]
Hi,

If you saw our videos of OSCeleton on vimeo you will see that we had some output of the depth sensor on our desktop. What we did was run the NiUserTracker Sample that ships with OpenNI, and run OSCeleton at the same time.

This should work without any problems if you are using windows or linux. It's not possible to do this on OSX yet.

I'm adding a viewer to the wishlist anyway because alot of people are requesting that feature :)

**Comment by wayfarerboy** [comment]
I didn't realise you could do that!  That's a simpler method for the time being (at least until the feature is implemented into OSCeleton). Thanks.
